# ========== Profile ========== #
# avatar
avatar: /avatar/marine.jpg
# author name
author: 
# signature
signature: 564239493
# SNS
social:
  email: 564239493@qq.com
  github: //github.com/564239493
  # weibo:
  # zhihu:
  # facebook:
  # twitter:
  # instagram:
  # stack-overflow:
  # linkedin:
# friends
#friends:
  # friendA: //www.baidu.com
  # friendB: //www.google.com
  # friendC :

# ========== Site ========== #
# title of the site
SEO_title: Marine's Blog
# main title
main_title: Marine's Blog
# subtitle
subtitle: Where there is a will,there is a way.
# site haeder image
site_header_image: /intro/bg.jpg
# post haeder image
post_header_image: /intro/bg1.jpg
# 404 image
_404_image: 'http://oumn0o088.bkt.clouddn.com/404.jpg'

# ========== Comment ========== #
# 目前只支持一键添加livere评论（因为懒），其他评论插件可自行添加
comment:
  # change the value of livere to your livere data-uid
  livere:

# ========== Analytics ========== #
# Busuanzi pv Analytics
busuanzi: true
# Baidu analytics
baidu_analytics:
# Google analytics
google_analytics:
# CNZZ analytics
CNZZ_analytics:

# ========== Others ========== #
# favicon
favicon: /assets/zt.ico
# truncate length (the default is 300)
truncate_length:
